version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  checkout_code:
    executor: python/default
    steps:
      - checkout
  pip_empty:
    executor: python/default
    steps:
      - python/install-packages:
          pkg-manager: pip
  pip_requirements:
    executor: python/default
    steps:
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip   
  pip_pytest:
    executor: python/default
    steps:
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
  pytest_run:
    executor: python/default
    steps:
      - run:
          name: Execute pytest
          command: |
            pytest --version

workflows:
  main_wf:
    jobs:
      - checkout_code
      - pip_empty:
        requires:
          - checkout_code
  #    - pip_requirements:
  #      requires:
  #        - pip_empty
  #    - pip_pytest:
  #      requires:
  #        - pip_requirements
  #    - pytest_run:
  #      requires:
  #        - pip_pytest
