version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:  # install only what is found in requirements.txt
          pkg-manager: pip
      - run:
          name: Execute pytest
          command: |
            pytest --version
      - python/install-packages:
          pip-dependency-file: requirements.txt  # you can specify a different requirements filename
          pkg-manager: pip   
      - python/install-packages:
          args: boto3
          pkg-manager: pip
          pypi-cache: false
  python_ver:
    executor: python/default
    steps:
      - run:
          name: Execute python
          command: |
            python --version

workflows:
  main_wf:
    jobs:
      - build
      - python_ver:
          requires:
            - build
