version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          name: pip 1
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          name: pip 2
          pkg-manager: pip
      - python/install-packages:
          name: pip 3
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Execute pytest
          command: |
            pytest --version

workflows:
  main:
    jobs:
      - build
