version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  checkout_code:
    executor: python/default
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - '*'
  pip_empty:
    executor: python/default
    steps:
          #at: ~/repo/workspace
      - python/install-packages:  # install only what is found in requirements.txt
          pkg-manager: pip
      - attach_workspace:
          at: ~/
  pip_requirements:
    executor: python/default
    steps:
      - python/install-packages:
          pip-dependency-file: requirements.txt  # you can specify a different requirements filename
          pkg-manager: pip   
  pip_pytest:
    executor: python/default
    steps:
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
  pytest_run:
    executor: python/default
    steps:
      - run:
          name: Execute pytest
          command: |
            pytest --version

workflows:
  main_wf:
    jobs:
      - checkout_code
      - pip_empty:
          requires:
            - checkout_code
    #  - pip_requirements:
    #      requires:
    #        - pip_empty
    #  - pip_pytest:
    #      requires:
    #        - pip_requirements
    #  - pytest_run:
    #      requires:
    #        - pip_pytest
